// Common conventions for all backend services.
plugins {
    id 'org.springframework.boot' version '3.5.6' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
}

ext {
    springdocVersion = '2.8.13'
    archunitVersion = '1.4.1'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'jacoco'

    group = 'com.andresyfr'
    version = '1.0.0'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    repositories {
        mavenCentral()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.compilerArgs.addAll(['-parameters', '-Xlint:unchecked', '-Xlint:deprecation'])
    }

    tasks.withType(Javadoc).configureEach {
        options.encoding = 'UTF-8'
        options.addStringOption('Xdoclint:all,-missing', '-quiet')
    }

    tasks.named('test') {
        useJUnitPlatform()
        finalizedBy tasks.named('jacocoTestReport')
    }

    tasks.named('jacocoTestReport') {
        dependsOn tasks.named('test')
        reports {
            xml.required = true
            html.required = true
        }
    }
}
